snapshot_dir: 'data/snapshots/'
log_dir: 'data/logs/'
epochs: 4000
row_size: 28
col_size: 28
channels: 1
num_classes: 10
knn_compare: False
activation_maps: False
hyper_optimization: True
random_labels: False
architecture: 'minivgg'
starting_checkpoint: ''
initial_epoch: 0
batch_size: 256
loss: 'categorical_crossentropy'
optimizer: 'SGD'
learning_rate: 0.1
weight_decay: 0.000001
dropout: 0.5
spatialdropout: 0.01
first_block: 32
second_block: 64