snapshot_dir: 'data/snapshots/'
log_dir: 'data/logs/'
architecture: 'minivgg'
epochs: 120
batch_size: 128
loss: 'categorical_crossentropy'
optimizer: 'SGD'
learning_rate: 0.1
row_size: 28
col_size: 28
channels: 1
num_classes: 10
knn_compare: False
activation_maps: False