snapshot_dir: 'data/snapshots/'
log_dir: 'data/logs/'
epochs: 400
row_size: 28
col_size: 28
channels: 1
num_classes: 10
hyper_optimization: False
random_labels: False
architecture: 'minivgg'
starting_checkpoint: ''
initial_epoch: 0
batch_size: 128
loss: 'categorical_crossentropy'
optimizer: 'SGD'
learning_rate: 0.0616
weight_decay: 0.0001
dropout: 0.55
spatialdropout: 0.027
first_block: 64
